[lib]
edition = "2021"

[package]
name = "decl_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
num-traits = "0.2.19"
paste = "1.0.15"
rustversion = "1.0.18"
static_assertions = "1.1.0"


[features]
nightly = []
